apiVersion: v1
kind: Pod
metadata:
  name: volume-sharing
spec:
  containers:
  - name: apache
    image: httpd
    volumeMounts:
    - mountPath: /data
      name: data-volume
  volumes:
  - name: data-volume
    hostPath:
      path: /vagrant/data-volume #directory on host
      type: Directory #optional 